//This code is solely to turn off the existing epilogues

//Viconia (if tries to kill all humans)
IF
	Global("StartEndBios","AR6200",1)  // The Throne of Bhaal
	InParty("Viconia")  // Viconia
	Global("_bAllRivvinMustDie","GLOBAL",1)  //Poisons everyone
	OR(2)
		!Global("ViconiaRomanceActive","GLOBAL",2)  //not romancing CN
		Global("PlayerChoseEssence","GLOBAL",1)   //Or CN becomes God
	Global("ViconiaBio","GLOBAL",0)
THEN
	RESPONSE #100
	SetGlobal("ViconiaBio","GLOBAL",3)
END

