
IF
	Global("_bViconiaMeetsImraeInTemple","GLOBAL",8)
	Name("UDDROW01",Myself)
	AreaCheck("AR2201")
	OR(2)
		Detect("Imrae")
		Detect([PC])
THEN
	RESPONSE #100
	SetGlobal("_bImraeMakesGuardsLeave","GLOBAL",1)
	EscapeArea()
END


IF
	GlobalGT("_bViconiaShoutsDemonDevir","GLOBAL",1)
	OR(3)
		See(Player1)
		See("demlord")
		See("Viconia")
THEN	
	RESPONSE #100
	DisplayStringNoNameHead(Myself,@1)
	EscapeArea()
END

