//If you side with Bodhi in her lair.
IF
	InParty("HaerDalis")
	AreaCheck("AR0809")
	Global("_bBodhiJoinsParty","GLOBAL",2)
	OR(2)
		Detect("_bBodhi")
		InParty("_bBodhi")
	IfValidForPartyDialog("Aerie") 
	Global("HaerDalisRomanceActive","GLOBAL",2)
THEN
	RESPONSE #100
	ChangeAIScript("haerdax",SPECIFICS) ChangeAIScript("useitem",GENERAL) ChangeAIScript("",DEFAULT)
	LeaveParty()
	Enemy()
	ClearAllActions()
	Continue()
END

