//If you have Imoen and Bodhi has her soul.
IF
	Global("_bBodhiHasSoul","GLOBAL",1)
	IfValidForPartyDialog(Myself)
	CombatCounter(0)
	Global("_bImoenObjectsBodhiToB","GLOBAL",0)
THEN
	RESPONSE #100
	SetGlobal("_bImoenObjectsBodhiToB","GLOBAL",1)
END

IF
	Global("_bImoenObjectsBodhiToB","GLOBAL",1)
THEN
	RESPONSE #100
	StartDialogNoSet(Player1)
END

IF
	Global("_bImoenObjectsBodhiToB","GLOBAL",2)
	InParty(Myself)
THEN
	RESPONSE #100
	LeaveParty() 
	EscapeArea()
END

