
//Jan's Dialogue in his house if everyone's dying.
IF
	Global("_bAllRivvinMustDie","GLOBAL",1)
	IfValidForPartyDialog("Jan")
	AreaCheck("AR0402") //Main floor, Jan's house.
	Global("_bGenocideJanTalksFamily","GLOBAL",0)
	Global("_bJanGenocideFamilyWorry","GLOBAL",1)
THEN
	RESPONSE #100
	SetGlobal("_bGenocideJanTalksFamily","GLOBAL",1)
END

IF
	Global("_bGenocideJanTalksFamily","GLOBAL",1)
THEN
	RESPONSE #100
	StartDialogNoSet(Player1) 
END

