//If you have Keldorn and he detects Bodhi
IF
	Detect("_bBodhi")
	GlobalGT("_bBodhiHasSoul","GLOBAL",0)
	IfValidForPartyDialog(Myself)
	CombatCounter(0)
	Global("_bKeldornObjectsBodhiToB","GLOBAL",0)
THEN
	RESPONSE #100
	SetGlobal("_bKeldornObjectsBodhiToB","GLOBAL",1)
END

IF
	Global("_bKeldornObjectsBodhiToB","GLOBAL",1)
THEN
	RESPONSE #100
	StartDialogNoSet(Player1)
END

IF
	Global("_bKeldornObjectsBodhiToB","GLOBAL",2)
	InParty(Myself)
THEN
	RESPONSE #100
	LeaveParty() 
	EscapeArea()
END

