IF //Korgan and Hexxat Scene Trigger. Next trigger in _bkorganevil.baf 
	Global("_BKorHex","GLOBAL",1)
	GlobalTimerExpired("_bkorganhextimer1","GLOBAL")
	IfValidForPartyDialogue("Korgan")
	IfValidForPartyDialogue("Hexxat")
	!Global("HexxatRomanceActive","GLOBAL",1)
	!Global("HexxatRomanceActive","GLOBAL",2)
	Global("_brestcheck","GLOBAL",0)
	!AreaType(DUNGEON)
	CombatCounter(0)
THEN
	RESPONSE #100
		SetGlobal("_BKorHex","GLOBAL",2)
		SetGlobal("_brestcheck","GLOBAL",2)
END
