//If you have Mazzy and she detects Bodhi
IF
	Detect("_bBodhi")
	Global("_bBodhiHasSoul","GLOBAL",1)
	IfValidForPartyDialog(Myself)
	CombatCounter(0)
	Global("_bMazzyObjectsBodhiToB","GLOBAL",0)
THEN
	RESPONSE #100
	SetGlobal("_bMazzyObjectsBodhiToB","GLOBAL",1)
END

IF
	Global("_bMazzyObjectsBodhiToB","GLOBAL",1)
THEN
	RESPONSE #100
	StartDialogNoSet(Player1)
END

IF
	Global("_bMazzyObjectsBodhiToB","GLOBAL",2)
	InParty(Myself)
THEN
	RESPONSE #100
	LeaveParty() 
	EscapeArea()
END

