//If you have Rasaad and he detects Bodhi
IF
	Detect("_bBodhi")
	Global("_bBodhiHasSoul","GLOBAL",1)
	IfValidForPartyDialog(Myself)
	CombatCounter(0)
	Global("_bRasaadObjectsBodhiToB","GLOBAL",0)
THEN
	RESPONSE #100
	SetGlobal("_bRasaadObjectsBodhiToB","GLOBAL",1)
END

IF
	Global("_bRasaadObjectsBodhiToB","GLOBAL",1)
THEN
	RESPONSE #100
	StartDialogNoSet(Player1)
END

IF
	Global("_bRasaadObjectsBodhiToB","GLOBAL",2)
	InParty(Myself)
THEN
	RESPONSE #100
	LeaveParty() 
	EscapeArea()
END

