// Aerie Flight Scene
IF
True()
THEN
RESPONSE #100
CutSceneId("Aerie")
SetInterrupt(FALSE)
CreateVisualEffectObject("SPPOLYMP","Aerie")
Wait(2)
ApplySpellRES("_bELFP","Aerie")
GiveItemCreate("_BWING","Aerie",0,0,0)
XEquipItem("_BWING","Aerie",SLOT_HELMET,EQUIP)
Wait(2)
CreateVisualEffectObject("SPSARMOR","Aerie")
Wait(2)
FadeToColor([20.0],0)
Wait(3)
MoveToObject("Edwin")
StartDialogNoSet(Player1)
END
