
//Clara- Anomen Talk 13/17 Trigger, next trigger in regular script
IF 
	IfValidForPartyDialog("Anomen")
	IfValidForPartyDialog("_bClara")
	GlobalTimerExpired("_bCALoveTime","GLOBAL")
	OR(2)
	Global("_bClaraAnomenLove","GLOBAL",31)
	Global("_bClaraAnomenLove","GLOBAL",43)
	Global("_brestcheck","GLOBAL",0)
THEN
	RESPONSE #100
	SetGlobal("_brestcheck","GLOBAL",2)
	IncrementGlobal("_bClaraAnomenLove","GLOBAL",1)
END


