//Trigger for Boo Cutscene
IF
	IfValidForPartyDialog("NEERA")
	IfValidForPartyDialog("Minsc")
	HaveKnownSpell(WIZARD_POLYMORPH_OTHER)
	!Global("NeeraRomanceActive","GLOBAL",2)
	!Global("NeeraRomanceActive","GLOBAL",1)
	Global("_bNeeraMinscLove","GLOBAL",40)
	Global("_bBooChange","GLOBAL",0)
	Global("_brestcheck","GLOBAL",0)
THEN
	RESPONSE #100
	SetGlobal("_bBooChange","GLOBAL",1)
	SetGlobal("_brestcheck","GLOBAL",2)
END

