// Gorion Wraith scene. Khalid dies and a bear appears and talks
IF
True()
THEN
RESPONSE #100
CutSceneId(Player1)
CreateVisualEffectObject("SPFDEATH","loveone2")
Wait(1)
ActionOverride("loveone2",DestroySelf())
Wait(1)
CreateVisualEffect("SPFLESHS",[1454.1398])
Wait(1)
CreateCreature("bdsha06a",[1454.1398],14)
ActionOverride("bdsha06a",SetDialog("_bBear1"))
Wait(1)
ActionOverride("bdsha06a",StartDialogueNoSet(Player1))
END
