//Trigger for 3rd Nalia Banter
IF 
	InParty("_bClara")
	InParty("Nalia")
	!StateCheck("Nalia",CD_STATE_NOTVALID) 
	!StateCheck("_bClara",CD_STATE_NOTVALID) 
	Global("_BBCLARANALIA","GLOBAL",3)
	GlobalTimerExpired("_bGirlsNightOut","GLOBAL")
	OR(2)
	AreaCheck("AR5501")	      //Amkethran Inn
	AreaCheck("AR5003")       //Saradush Tavern - tankard tree
	Global("_brestcheck","GLOBAL",0)
THEN
	RESPONSE #100
	SetGlobal("_brestcheck","GLOBAL",2)
	SetGlobal("_BBCLARANALIA","GLOBAL",4)
END
