IF	//Script for triggering Renal's conversation with OHHFAK about Dragomir's Tomb
	See("Renal Bloodscalp")
	InParty("OHHFAK")
	!StateCheck("OHHFAK",CD_STATE_NOTVALID)
	Global("_bRenalOHHFAK","GLOBAL",0)
THEN
	RESPONSE #100
	SetGlobal("_bRenalOHHFAK","GLOBAL",1)
END

IF
	Detect("Renal Bloodscalp")
	InParty("OHHFAK")
	!StateCheck("OHHFAK",CD_STATE_NOTVALID)
	Global("_bRenalOHHFAK","GLOBAL",1)
THEN
	RESPONSE #100
	ActionOverride("Renal Bloodscalp",StartDialogNoSet(Player1))
END
