//Bodhi first joining you.
IF
	True()
THEN
	RESPONSE #100
	CutSceneId(Player1)
	SetInterrupt(FALSE)
	FadeToColor([20.0],0)
	CreateCreatureObject("_bBodhi","c6Bodhi",0,0,0)
	SetGlobal("_bBodhiHasSoul","GLOBAL",1) 
	SetGlobal("_bBodhiJoinsParty","GLOBAL",1)  
	ActionOverride("c6Bodhi",Kill("c6Bodhi"))
	Wait(1)
	ActionOverride("c6Bodhi",DestroySelf())
	FadeFromColor([20.0],0)
	ActionOverride("_bBodhi",StartDialogNoSet(Player1))
END

