//Bodhi first joining you.
IF
	True()
THEN
	RESPONSE #100
	CutSceneId("_bBodhi")
	SetInterrupt(FALSE)
	ActionOverride("suelle2",ForceSpell("_bBodhi",FLASHY_1))
	Wait(3)
	Polymorph(FIGHTER_FEMALE_ELF)
	ApplySpellRES("_BBODELF","_bBodhi")
	Wait(1)
	SetGlobal("_bBodhiBecomesElf","GLOBAL",1)
	SetGlobal("_bBodhiEllesimeDialogue","GLOBAL",1)
	SetGlobal("_bBodhiHasSoul","GLOBAL",2)
	ActionOverride("suelle2",StartDialogNoSet(Player1))
END

