
IF
	Global("_bBodhiBecomesElf","GLOBAL",1)
	Global("_bFirstBodhiElfDialogue","GLOBAL",0)
THEN
	RESPONSE #100
	SetGlobal("_bFirstBodhiElfDialogue","GLOBAL",1)
END

IF
	Global("_bFirstBodhiElfDialogue","GLOBAL",1)
	Detect([PC])
THEN
	RESPONSE #100
	PlaySong(0) 
	PlaySound("_bBoMu01")
	StartDialogNoSet(Player1)
END

IF
	InParty("_bBodElf")
	Global("_bFirstBodhiElfXP","GLOBAL",0)
THEN
	RESPONSE #100
	AddXPObject("_bBodElf",4250000)
	SetGlobal("_bFirstBodhiElfXP","GLOBAL",1)
END
